config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  resources :restaurants, only: [:new, :create, :show, :index] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  RATINGS = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant

  validates :rating, inclusion: { in: RATINGS }, numericality: { only_integer: true }
  validates :restaurant_id, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
    @title = if @restaurants.count == 0
      "Aucun restaurant"
    elsif @restaurants.count == 1
      "1 restaurant"
    else
      "#{@restaurants.count} restaurants"
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private 

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>RailsYelpMvp</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/restaurants/index.html.erb
<%= render './navbar' %>
<div class="container">
	<div class="head">
		<h1><%= @title %></h1>
	</div>
	<% @restaurants.each do |r| %>
		<div class="card container my-3 p-3">
			<p><%= link_to r.name, restaurant_path(r) %><br>
				<%= r.category %>
			</p>
			<p><i class="fas fa-map-marker-alt"></i> <%= r.address %><br>
				<i class="fas fa-phone"></i> <%= r.phone_number %> </p>
		</div>
	<% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<div class="container">
    <%= simple_form_for [@restaurant] do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category, as: :select, collection: Restaurant::CATEGORY %>
        <%= f.submit "add a restaurant", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/restaurants/show.html.erb
<%= render './navbar' %>
<div class=" container m-3">
    <h1><%= @restaurant.name %></h1>
    <h4><%= @restaurant.address %></h4>
    <p><%= @restaurant.category %> restaurant</p>
    <%= link_to 'New review', new_restaurant_review_path(@restaurant), class: "btn btn-primary my-3" %>
    <% @reviews.each do |r| %>
      <div class="card p-2 my-3">
        <p><em><%= r.content %></em><br>
        <% r.rating.times do %>
          <span class="fas fa-star"></span>
        <% end %>
        <% (5 - r.rating).times do %>
          <span class="far fa-star"></span>
        <% end %>
        </p>
      </div>
    <% end %>
</div>




















   

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, as: :select, collection: Review::RATINGS %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>